import { Component, Input } from '@angular/core';
import { ScheduleFile } from 'src/app/models/schedule-file';
import { isDevMode } from '@angular/core';

@Component({
  selector: 'app-accordion',
  templateUrl: './accordion.component.html',
  styleUrls: ['./accordion.component.scss'],
})
export class AccordionComponent {
  @Input()
  scheduleFile?: ScheduleFile;

  ngOnInit() {
    if (isDevMode()) {
      this.initSchedule(true);
    }
  }

  initSchedule(withErrors: boolean = false) {
    this.scheduleFile = {
      id: undefined,
      name: 'CARLA.xlsx',
      weeks: [
        {
          id: undefined,
          name: 'SEMANA 1',
          days: [
            {
              id: undefined,
              name: 'LUNES',
              start: '15:00',
              end: '23:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'MARTES',
              start: '15:00',
              end: '23:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'MIÉRCOLES',
              start: '15:00',
              end: '23:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'JUEVES',
              start: '14:00',
              end: '20:30',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'VIERNES',
              start: '09:00',
              end: '15:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'SÁBADO',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
            {
              id: undefined,
              name: 'DOMINGO',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
          ],
          totalHours: 37.5,
          workHours: 36.75,
          breakHours: 0.75,
          nightHours: 3.75,
          errors: [],
          hasErrors: false,
        },
        {
          id: undefined,
          name: 'SEMANA 2',
          days: [
            {
              id: undefined,
              name: 'LUNES',
              start: '07:00',
              end: '15:30',
              isFree: false,
              errors: withErrors ? ['Más de 7 días de trabajo seguidos'] : [],
            },
            {
              id: undefined,
              name: 'MARTES',
              start: '07:00',
              end: '15:30',
              isFree: false,
              errors: withErrors ? ['Más de 7 días de trabajo seguidos'] : [],
            },
            {
              id: undefined,
              name: 'MIÉRCOLES',
              start: '07:00',
              end: '15:00',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'JUEVES',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
            {
              id: undefined,
              name: 'VIERNES',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
            {
              id: undefined,
              name: 'SÁBADO',
              start: '15:00',
              end: '21:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'DOMINGO',
              start: '15:00',
              end: '21:15',
              isFree: false,
              errors: [],
            },
          ],
          totalHours: 37.5,
          workHours: 36.75,
          breakHours: 0.75,
          nightHours: 0,
          errors: [],
          hasErrors: withErrors,
        },
        {
          id: undefined,
          name: 'SEMANA 3',
          days: [
            {
              id: undefined,
              name: 'LUNES',
              start: '14:00',
              end: '21:30',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'MARTES',
              start: '14:00',
              end: '21:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'MIÉRCOLES',
              start: '14:00',
              end: '21:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'JUEVES',
              start: '15:30',
              end: '23:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'VIERNES',
              start: '15:30',
              end: '23:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'SÁBADO',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
            {
              id: undefined,
              name: 'DOMINGO',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
          ],
          totalHours: 37.5,
          workHours: 36.25,
          breakHours: 1.25,
          nightHours: 2.5,
          errors: [],
          hasErrors: false,
        },
        {
          id: undefined,
          name: 'SEMANA 4',
          days: [
            {
              id: undefined,
              name: 'LUNES',
              start: '07:00',
              end: '14:30',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'MARTES',
              start: '07:00',
              end: '14:30',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'MIÉRCOLES',
              start: '07:00',
              end: '14:30',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'JUEVES',
              start: '07:00',
              end: '14:30',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'VIERNES',
              start: '07:00',
              end: '14:30',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'SÁBADO',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
            {
              id: undefined,
              name: 'DOMINGO',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
          ],
          totalHours: 37.5,
          workHours: 36.25,
          breakHours: 1.25,
          nightHours: 0,
          errors: [],
          hasErrors: false,
        },
        {
          id: undefined,
          name: 'SEMANA 5',
          days: [
            {
              id: undefined,
              name: 'LUNES',
              start: '14:45',
              end: '23:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'MARTES',
              start: '14:45',
              end: '23:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'MIÉRCOLES',
              start: '14:45',
              end: '23:15',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'JUEVES',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
            {
              id: undefined,
              name: 'VIERNES',
              start: undefined,
              end: undefined,
              isFree: true,
              errors: [],
            },
            {
              id: undefined,
              name: 'SÁBADO',
              start: '09:00',
              end: '15:00',
              isFree: false,
              errors: [],
            },
            {
              id: undefined,
              name: 'DOMINGO',
              start: '09:00',
              end: '15:00',
              isFree: false,
              errors: [],
            },
          ],
          totalHours: 37.5,
          workHours: 36.75,
          breakHours: 0.75,
          nightHours: 3.75,
          errors: [],
          hasErrors: false,
        },
      ],
    };
  }
}
